### ISSUE TITLE
Hotkey support

### ISSUE THREAD

**Issue by AlexBezuska** [muffinmad/atom-textile-preview#1]
Would it be possible to add the hotkey (maybe ctrl-shift-t) similar to markdown-preview

Here is how they implement it in `markdown-preview.cson'

```
'atom-workspace, atom-workspace atom-text-editor':
  'ctrl-shift-m': 'markdown-preview:toggle'
```

**Comment by muffinmad** [comment]
You can define your own hotkey in your keymap.cson like this:
```
'atom-text-editor':
  'ctrl-shift-t': 'textile-preview:toggle'
```
But ctrl-shit-t is used to reopen closed tab and ctrl-alt-t is for nuclide fuzzy finder. Thats why i don't like making the default hotkey. There are too many hotkeys already.
