### ISSUE TITLE
Deprecated selector in `textile-preview/styles/textile-preview.less`

### ISSUE THREAD

**Issue by diomat** [muffinmad/atom-textile-preview#2]
In `textile-preview/styles/textile-preview.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.scrollbars-visible-always .textile-preview atom-text-editor::shadow .vertical-scrollbar,
.scrollbars-visible-always .textile-preview atom-text-editor::shadow .horizontal-scrollbar` => `.scrollbars-visible-always .textile-preview atom-text-editor.editor .vertical-scrollbar,
.scrollbars-visible-always .textile-preview atom-text-editor.editor .horizontal-scrollbar`

* `.scrollbars-visible-always .textile-preview atom-text-editor:hover::shadow .vertical-scrollbar,
.scrollbars-visible-always .textile-preview atom-text-editor:hover::shadow .horizontal-scrollbar` => `.scrollbars-visible-always .textile-preview atom-text-editor:hover.editor .vertical-scrollbar,
.scrollbars-visible-always .textile-preview atom-text-editor:hover.editor .horizontal-scrollbar`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by muffinmad** [comment]
Fixed in https://github.com/muffinmad/atom-textile-preview/commit/222f098535d949bf980d43c5816d20b2e03418ae
